### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by Phasip**
Include external resource for nameservers, otherwise we always remove servers but never get new ones.
Added a sort random & unique in the end to remove duplicates generated from the two nameserver sources.

### CODE REVIEW

**Comment by dee-see** [comment]
That would be great, the list had 23 resolvers just at the [beginning of the year](https://github.com/janmasarik/resolvers/blob/bde360f7c7a79d0077f25a5436ed29576912cf8b/resolvers.txt) and it's down to 15 now.

WDYT @janmasarik ?

**Comment by dee-see** [comment]
Hmm I just ran dnsvalidator on the public resolvers list and the result is unfortunately not great on the first loop.

**Comment by Phasip** [comment]
Hello! Since no reply was made to the pull request I continued here: https://github.com/Phasip/resolvers

A few notes:
The public list is not great after one run. I fixed this by having multiple resolver lists where the dns server had worked for the last x attempts.
Using the public list takes too long for github actions from time to time. I fixed this by increasing the number of threads on the resolver and decreasing the timeout.

**Comment by dee-see** [comment]
Sweet, thanks for sharing :)

**Pull request closed without merging**
